### ISSUE TITLE
PARIS formatting not differentiating some countries

### ISSUE THREAD

**Issue by hdelongueville** [ACRG-Bristol/acrg#190]
**Describe the bug**
When formatting East Asian inversions with the country file '/group/chem/acrg/LPDM/countries/country_splitChina-splitJapan_EASTASIA.nc', the paris outputs contain duplicated 'PRK' instead of differentiating 'KOR' from 'PRK' ('REPUBLIC OF KOREA' and "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA"). 

Note that country_splitChina-splitJapan_EASTASIA.nc contains 
array(['OCEAN', 'VIET NAM', 'UZBEKISTAN', 'MARSHALL ISLANDS',
       'NORTHERN MARIANA ISLANDS', 'UNITED STATES',
       'UNITED ARAB EMIRATES', 'TURKMENISTAN', 'THAILAND', 'TAJIKISTAN',
       'TAIWAN', 'SRI LANKA', 'REPUBLIC OF KOREA', 'SINGAPORE',
       'SAUDI ARABIA', 'RUSSIAN FEDERATION', 'PHILIPPINES',
       'PAPUA NEW GUINEA', 'PAKISTAN', 'OMAN',
       "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA", 'NEPAL', 'MONGOLIA',
       'MALAYSIA', "LAO PEOPLE'S DEMOCRATIC REPUBLIC", 'KYRGYZSTAN',
       'KIRIBATI', 'KAZAKHSTAN', 'EAST JAPAN', 'IRAN', 'INDONESIA',
       'INDIA', 'CHINA', 'HONG KONG', 'CAMBODIA', 'MYANMAR',
       'BRUNEI DARUSSALAM', 'BHUTAN', 'BANGLADESH', 'AFGHANISTAN',
       'EAST CHINA', 'WEST JAPAN'], dtype='<U37')

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here including environment details / OS being used if relevant.

**Comment by hdelongueville** [comment]
@brendan-m-murphy Is this related to an issue in iso3166.json or in /group/chem/acrg/LPDM/countries/country_splitChina-splitJapan_EASTASIA.nc? If it is the latter then I'll close the issue as it is not related to paris_formatting specifically.

**Comment by brendan-m-murphy** [comment]
It's possible that the way that alternate names are looked up is conflating North and South Korea.

**Comment by brendan-m-murphy** [comment]
This part:
``` 
# next try to match substrings...
    for v in iso3166.values():
        names = [v["iso_long_name"].lower()] + [name.lower() for name in v["unofficial_names"]]
        if any(x.lower() in name for name in names):
            return v[code]
```

Could match with PRK first since "DEMOCRATIC..." comes before "REPUBLIC...". I could try to look at all matches and take the closest one... I guess the name for South Korea in the country file must not be exact matches for any of the official or unofficial names (maybe a formatting issue?)

**Comment by brendan-m-murphy** [comment]
So the names in the country file don't match exactly because the official names in the iso3166 file start with "The..." (like "The Republic of Korea"), so it has to match the substring "Republic of Korea", and it matches "The Democratic People's Republic of Korea", and returns the code from that.

So.. maybe I will try removing leading "The " values before matching substrings...

**Comment by hdelongueville** [comment]
Awesome! Thanks for fixing this!
